name: Deploy from Issue

on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: write

jobs:
  deploy:
    if: contains(github.event.issue.labels.*.name, 'deployment')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
#      - name: Debug Issue Body
#        run: |
#          ISSUE_NUMBER=${{ github.event.issue.number }}
#          REPO=${{ github.repository }}

#          # Fetch issue details
#          ISSUE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER")

#          echo "Raw Issue Data:"
#          echo "$ISSUE_DATA"

      - name: Extract Issue Inputs
        id: extract
        run: |
          ISSUE_NUMBER=${{ github.event.issue.number }}
          REPO=${{ github.repository }}

          # Fetch issue details
          ISSUE_DATA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/$REPO/issues/$ISSUE_NUMBER")

          # Extract issue body
          ISSUE_BODY=$(echo "$ISSUE_DATA" | jq -r '.body')

          # Debug issue body
          echo "---- Issue Body ----"
          echo "$ISSUE_BODY"
          echo "--------------------"

          # Extract environment and region using awk
          ENVIRONMENT=$(echo "$ISSUE_BODY" | awk -v RS= '/^### Environment/ {getline; print}' | xargs)
          REGION=$(echo "$ISSUE_BODY" | awk -v RS= '/^### Region/ {getline; print}' | xargs)

          # Validate extracted values
          if [[ -z "$ENVIRONMENT" || -z "$REGION" ]]; then
            echo "❌ Error: Environment or Region is empty!"
            exit 1
          fi

          echo "✅ Extracted Environment: $ENVIRONMENT"
          echo "✅ Extracted Region: $REGION"

          # Save to GitHub environment variables
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "REGION=$REGION" >> $GITHUB_ENV



      - name: Verify Deployment Path
        run: |
          DEPLOYMENT_PATH="deployments/$ENVIRONMENT/$REGION"
          if [ ! -d "$DEPLOYMENT_PATH" ]; then
            echo "❌ Error: Deployment path $DEPLOYMENT_PATH does not exist!"
            exit 1
          fi
          echo "✅ Deploying from $DEPLOYMENT_PATH"

      - name: Initialize Terraform
        run: |
          DEPLOYMENT_PATH="deployments/$ENVIRONMENT/$REGION"
          echo $DEPLOYMENT_PATH
          cd $DEPLOYMENT_PATH
          ls -la
          bash test.sh

#      - name: Apply Terraform
#        run: |
#          cd $DEPLOYMENT_PATH
#          terraform apply -auto-approve

      - name: Comment on Issue
        run: |
          COMMENT_BODY="✅ Deployment started for **$ENVIRONMENT/$REGION**"
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d "{\"body\": \"$COMMENT_BODY\"}" \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments"

      - name: Close the issue
        run: |
          echo "✅ Closing issue after deployment approval."
          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state": "closed"}' \
          "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}"
      
      
